---
fail_fast: false

default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args:
          - --update-only
          - --maxlevel
          - "3"
          - --github
          - --notitle

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .yamllint.yaml

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-crlf
        exclude: (dist/index.mjs)
      - id: remove-tabs
        exclude: (dist/index.mjs|dist/595.index.mjs)

  - repo: https://github.com/sirosen/texthooks
    rev: 0.4.0
    exclude: (dist/**)
    hooks:
      - id: fix-smartquotes
        exclude: (dist/index.mjs)
      - id: fix-ligatures
      - id: forbid-bidi-controls

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=100
        exclude: (dist/index.mjs|package-lock.json)
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        exclude: (dist/index.mjs|src/commit.mjs)
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: (dist/index.mjs)
        args:
          - --fix=auto
      - id: trailing-whitespace
        exclude: (dist/index.mjs)
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint-fix
        args:
          - --config
          - .markdownlint.yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        args:
          - --ignore-path
          - .prettierignore
          - --config
          - .prettierrc.js

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
